openapi: 3.0.0
info:
  version: 1.0.0
  title: Quotaday
  description: An API to access quotes
paths:
  /quote:
    get:
      description: Returns a quotation
      parameters:
        - name: id
          in: query
          description: Identifies the i-th quotation to return
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returned a quotation
          content:
            text/html:
              schema:
                type: string
                example: "Start before you are ready. Don't prepare, begin.\nMel Robbins"
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '400':
          $ref: '#/components/responses/Error'
    post:
      description: Lets a user post a new quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quote'
      responses:
        '200':
          description: Successfully created a new quote
          content:
            application/json:
             schema:
               $ref: '#/components/schemas/Quote'
        default:
          $ref: '#/components/responses/Error'
components:
  schemas:
    Quote:
      type: object
      required:
      - quote
      properties:
        author:
          type: string
          example: "Mel Robbins"
        quote:
          type: string
          example: "Start before you are ready. Don't prepare, begin."
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
                example: "400"
              message:
                type: string
                example: "Bad Request"
            required:
              - code
              - message
